# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dtWOrm38IIejEdJacOX7mVsOgYXIFwiD
"""

import numpy as np
import pandas as pd

student = ({"id":[1,2,3,4,5],
           "names":["ahmed","mohamed","so","os","ahmed"],
           "age":[20,30,15,25,40]
           })
student

df = pd.DataFrame(student)
df

names = ['ahmed', 'mohamed', 'so', 'os', 'ahmed']
age = [20, 30, 15, 25, 40]
series = pd.Series(index = age,data = names)
series

df

arr = np.random.randint(5,100,(100,3))
arr

arr_df = pd.DataFrame(arr,columns=["first","second","third"],index=[2*i for i in range(100)])
arr_df

pd1 = pd.read_csv("/content/main dataset.csv")
pd1.head(5)
#pd1.info()

pd1.describe().round()





pd1 = pd.read_excel("/content/dataset.xlsx",sheet_name = "Sheet1")
pd1.head(5)
#pd1.info()

print(pd1[-2:-1])

pd1.iloc[0:2,0]

pd1.loc[[0,5,150],["smiles","label"]]

def act5(act):
  return str(9)+act

xx = pd1["smiles"].apply(act5)
print(xx)
print("########")
print(pd1["Activity"])

pd1.sort_values(by="smiles")

df1=pd.read_csv("/content/Decoys.csv")
df2=pd.read_csv("/content/main dataset.csv")
data = pd.concat([df1,df2],axis=1)
data

df2[(df2.label=="Active") & (df2.Activity<10)]

df3 = df2.set_index("Activity")
df3

df2["label"]=="Active"

df2.columns