# -*- coding: utf-8 -*-
"""pandas_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dtWOrm38IIejEdJacOX7mVsOgYXIFwiD
"""

import pandas as pd
import numpy as np

df = pd.read_csv("50_Startups.csv")
print("-----------------------------------------------------")
print("-----------------------------------------------------")
print("-----------------------------------------------------")
print(df.shape)

df.head(5)
print("------------------------------------------")

print(df[df.State.isin(["New York"])])
print("------------------------------------------")

print(df["State"].value_counts())    #to show number of values in states column
print("------------------------------------------")


df["Names"] = "nemo"                 #if this column is found then replace the
                                     #values with nemo else create new column with nemo values
print(df.head(5))
print("------------------------------------------")




df["Administration"] = "xx"
print(df["Administration"])
print("------------------------------------------")


#df.isnull()
print(df["Administration"].isnull())
print("------------------------------------------")

print(df.isnull().sum())
print("------------------------------------------")

print(df["Administration"].isnull().sum())
print("------------------------------------------")

df.dropna(axis = "columns",inplace = False)#if True change the main data & False don't change main data
print(df.shape)
df.dropna(axis = "columns",inplace = True)#if True change the main data & False don't change main data
print(df.shape)

print(df)
print("------------------------------------------")

print(df.shape)
df.dropna(subset = ["Administration"],inplace=True)
print(df.shape)

df.loc[df['Administration'].isna()]

df.fillna({"Administration":"not avalible"},inplace = True)
df
print("---------------------------------------------------------------------------------------------------------")
print(df.loc[df['Administration'].isna()])  #show the location of the null values
df.fillna(method="ffill")#fill with before value

df1 = df["Administration"].replace(np.nan,"nemo")
df1#.isna().sum()




dic1 = {"ID":[1,2,3,4,5],
        "Name":["a","b","c","d","f"]}
dic2 = {"ID":[5,2,3,4,6],
        "Name":["g","h","l","m","n"]}
df1 = pd.DataFrame(dic1)
df2 = pd.DataFrame(dic2)
print(df1)
print(df2)

c = pd.merge(df1,df2,how = "inner",on = "ID")
c

c = pd.merge(df1,df2,how = "outer",on = "ID")
c

c = pd.merge(df1,df2,how = "left",on = "ID")
c

c = pd.merge(df1,df2,how = "right",on = "ID")
c

dic1 = {"date":["1/1/2000","1/2/2000","1/3/2000","1/4/2000","1/5/2000"],
        "Name":["g","h","l","m","n"]}
df1 = pd.DataFrame(dic1)
df1.info()

df1["date"]= pd.to_datetime(df1["date"])
df1.info()

#df1.to_csv("saved_files/50_Startups_update.csv")

# df = pd.read_csv("50_Startups.csv")
# print("-----------------------------------------------------")
# print("-----------------------------------------------------")
# print("-----------------------------------------------------")
# print(df.shape)
# print(df)

# print("//////////////////////////////////////////////////////")
# print(df["Profit"])
# print(df.isnull().sum())

# print(df["R&D Spend"])
# df.dropna(axis="columns",inplace=False)
# print(df.shape)
# df.fillna({"R&D Spend":"not available"},inplace=True)
# print(df["R&D Spend"])
# print(df.loc[df['R&D Spend'].isna()])

# print("//////////////////////////////////////////////////////")



# dic1 = {"date":["1/1/2000","1/2/2000","1/3/2000","1/4/2000","1/5/2000"],
#         "Name":["g","h","l","m","n"]}
# df1 = pd.DataFrame(dic1)
# print(df1.info())

# df1["date"]= pd.to_datetime(df1["date"])
# print(df1.info())






