# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1krYGbKcfx-PSAWlOQ5-LEs7dkykgokk5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

flights = sns.load_dataset("flights")
flights.head(5)

x_feb = flights[flights['month']=='Feb']
x_feb

sns.set_style("darkgrid")
sns.lineplot(x="year",y="passengers",data= x_feb)

sns.set_style("darkgrid")
sns.lineplot(x="year",y="passengers",data= x_feb)
plt.title("Year vs. ")
plt.xlabel("Year")
plt.ylabel("Passengers")

sns.set_style("darkgrid")
sns.lineplot(x="year",y="passengers",data= flights,hue='month')
plt.title("Year vs. ")
plt.xlabel("Year")
plt.ylabel("Passengers")

sns.set_style("darkgrid")
sns.lineplot(x="year",y="passengers",data= flights,style='month')
plt.title("Year vs. ")
plt.xlabel("Year")
plt.ylabel("Passengers")

plt.figure(figsize=(5,5))
sns.set_style("darkgrid")
sns.lineplot(x="year",y="passengers",data= flights,hue='month')
plt.title("Year vs. ")
plt.xlabel("Year")
plt.ylabel("Passengers")

fmri = sns.load_dataset("fmri")
fmri.head(5)

plt.figure(figsize=(5,5))
sns.set_style("ticks")
sns.lineplot(data= fmri,x="timepoint",y="signal",hue='event',style='region')
plt.title("Year vs. ")
plt.xlabel("Year")
plt.ylabel("Passengers")

plt.figure(figsize=(5,5))
sns.set_style("ticks")
sns.relplot(data= fmri,x="timepoint",y="signal",hue='event',style='region',kind='line',col='event',row='region')
plt.xlabel("Year")
plt.ylabel("Passengers")

"""Scatter plot"""

# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns

# tips = sns.load_dataset("tips")
# tips.head()

# sns.scatterplot(x='total_bill',y= "tip",data= tips)

# sns.scatterplot(x='total_bill',y= "tip",data= tips,hue="sex")

# sns.scatterplot(x='total_bill',y= "tip",data= tips,hue="sex",style="smoker")

# sns.scatterplot(x='total_bill',y= "tip",data= tips,hue="sex",style="smoker",size="size")

# sns.scatterplot(x='total_bill',y= "tip",data= tips,hue="sex",style="smoker",size="size",palette="plasma")



# sns.relplot(x='total_bill',y= "tip",data= tips,hue="time",style="sex",markers={"Male":"D","Female":"X"},kind="scatter")

# sns.relplot(x='total_bill',y= "tip",data= tips,hue="time",style="sex",col="sex")

# sns.relplot(x='total_bill',y= "tip",data= tips,hue="time",style="sex",col="sex")

# sns.relplot(x='total_bill',y= "tip",data= tips,hue="time",style="sex",col="sex",row="smoker")

# sns.regplot(x='total_bill',y= "tip",data=tips )

# sns.regplot(x='size', y= "tip",data = tips )

# sns.regplot(x='size', y= "tip",data = tips,x_jitter = 0.1 )

# sns.regplot(x='size', y= "tip",data = tips,x_estimator =np.mean )